// AI/Communication/composition/MessageBlueprint.js
// Message Blueprint — the structured plan that Composition builds and the
// Provider Translator converts into a provider-specific prompt.
// Authority: Part 6 — Composition System

export const RESPONSE_PATTERNS={conversation:{name:'conversation',sections:['greeting','answer','suggestion'],desc:'Simple greeting→answer→suggestion'},question:{name:'question',sections:['context','direct_answer','details','references'],desc:'Question with context'},research:{name:'research',sections:['question','overview','sources','combined_analysis','summary','references'],desc:'Multi-source research'},repository:{name:'repository',sections:['overview','relevant_files','key_classes','suggested_changes','summary'],desc:'Codebase analysis'},comparison:{name:'comparison',sections:['overview','item_a','item_b','comparison_table','verdict','references'],desc:'Side-by-side comparison'},troubleshooting:{name:'troubleshooting',sections:['problem','diagnosis','solutions','prevention','references'],desc:'Problem→diagnosis→solution'},explanation:{name:'explanation',sections:['topic','definition','details','examples','related_topics'],desc:'In-depth explanation'},tutorial:{name:'tutorial',sections:['goal','prerequisites','steps','tips','next_steps'],desc:'Step-by-step guide'},decision:{name:'decision',sections:['context','options','tradeoffs','recommendation','rationale'],desc:'Decision guidance'}};
export function selectPattern(t,c){if(t==='repository')return RESPONSE_PATTERNS.repository;if(t==='live')return RESPONSE_PATTERNS.question;if(t==='message')return RESPONSE_PATTERNS.conversation;if(c==='complex')return RESPONSE_PATTERNS.research;return RESPONSE_PATTERNS.question;}
let _id=0;export function createFact(t,s,p,c,u){return{id:'fact-'+(++_id),text:t,source:s,provider:p,confidence:c||0.5,url:u||null,citation:u?'['+p+']('+u+')':'['+p+']'};}
export function deduplicateFacts(f){const seen=new Set();return f.filter(x=>{const k=x.text.toLowerCase().replace(/\s+/g,' ').trim().slice(0,80);if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>b.confidence-a.confidence);}
export function createBlueprint(sec,o){o=o||{};return{overview:o.overview||'',sections:sec,summary:o.summary||'',conclusion:o.conclusion||null,citations:o.citations||[],tone:o.tone||'friendly',audience:o.audience||'discord',pattern:o.pattern||'question',metadata:{query:o.query||'',topic:o.topic||'web',complexity:o.complexity||'simple',timestamp:new Date().toISOString()}};}
export function blueprintToResponse(b){return{overview:{text:b.overview,citations:[]},sections:b.sections.map(s=>({...s,facts:s.facts.map(f=>({...f}))})),summary:{text:b.summary,keyPoints:b.sections.flatMap(s=>s.facts.slice(0,2)).map(f=>f.text)},conclusion:b.conclusion?{text:b.conclusion,verdict:null,sources:[]}:null,citations:b.citations,metadata:{...b.metadata,tone:b.tone,audience:b.audience,pattern:b.pattern}};}
